#!/bin/bash

die() {
    echo "$*" >&2
    exit 1
}

echo "Current working directory: $(pwd)"
yumdownloader --source binutils || die "Failed to download binutils SRPM"
rpm -hiv binutil*.src.rpm || die "Failed to install binutils SRPM"

cd /root/rpmbuild/SPECS || die "Failed to change to SPECS directory"
yum-builddep -y binutils.spec || die "Failed to gather the build dependencies for binutils"
patch -p0 << END
--- binutils.spec.orig  2017-01-31 09:24:18.988130013 -0500
+++ binutils.spec       2017-01-31 09:25:38.975347558 -0500
@@ -263,6 +263,11 @@
     ;;
 esac
 
+case %{binutils_target} in x86_64*|i?86*|arm*|aarch64*)
+  CARGS="$CARGS --enable-targets=x86_64-pep"
+  ;;
+esac
+
 %if 0%{?_with_debug:1}
 CFLAGS="$CFLAGS -O0 -ggdb2 -Wno-error -D_FORTIFY_SOURCE=0"
 %define enable_shared 0
END
rpmbuild -ba binutils.spec || die "Failed to build binutils"
cd ../RPMS/x86_64/
rpm -U binut*.rpm || die "Failed to install binutils RPM"
cd /root
rm -rf rpmbuild
